### ISSUE TITLE
Login does not work

### ISSUE THREAD

**Issue by marcvs** [dCache/dcache-view#205]
Steps to reproduce:

- visit https://prometheus.desy.de:3880
- click "log in" in top right
- Choose "Login via an OpenID account"
    - This is actually OpenID Connect !
- Choose HDF-AAI
- Login Via HDF-AAI
- I'm back at the login screen.
- From now on I can repeat the steps (login via HDF-AAI) but I'm immediately returned to the page where I can choose local account vs "OpenID"

Ah, and I tried deploying an account via feudal first, but this stays in "circle" mode

**Comment by femiadeyemi** [comment]
Hi @marcvs, thank you for pointing this out and for describing the steps, it is very helpful. I followed steps but I choose the EXtreme Data Cloud option and it seem to work. Since I don't have account with HDF-AAI, I can really test what is going on. I will talk to @paulmillar and get back to you as soon as possible.

**Comment by paulmillar** [comment]
Hi @marcvs 
I see three failed login attempts (in close succession), at
- 20 Nov 2019 17:05:52
- 20 Nov 2019 17:08:55
- 20 Nov 2019 17:09:29

I'm guessing these are from the problem you described here.

The problem comes from dCache not knowing who you are.  Information about you is discovered via OIDC, but there's no corresponding dCache account, so the login fails.

Both Femi's (XDC) and my (XDC and HDF) identities are registered against our respective accounts, so we can log in without any problem.

I can add you manually or alternatively, we can get the feudal account provisioning service working.

Which would you prefer?

**Comment by marcvs** [comment]
I think we should do this via feudal (or course :D)

**Comment by paulmillar** [comment]
It turns out that the feudal agent wasn't running on prometheus.

It's now started, but with the limitation that registered users are lost when dCache is rebuilt in the morning.

Could you try registered again?

You may need to unregistered and re-register (through feudal) to ensure your account on prometheus exists.

**Comment by marcvs** [comment]
Yes it works now.

You might want to provide some information in the "credentials" dict. Such as hostname or url to visit

**Comment by femiadeyemi** [comment]
Should I consider this issue resolved?

**Comment by marcvs** [comment]
Yes, I just checked again: It's solved.

M.

On 11/22/19 14:06, femiadeyemi wrote:
> Should I consider this issue resolved?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/dCache/dcache-view/issues/205#issuecomment-557712166

-- 
Marcus.
