### ISSUE TITLE
Allow sorting file listings etc

### ISSUE THREAD

**Issue by ZNikke** [dCache/dcache-view#285]
Currently dCache View displays files/directories in server (random) order.

This unfortunately makes the service very unfriendly for users, it's been one of the first complaints from test users and early adopters.

We propose to add functionality to sort items in lists, primarily the file/directory listings but preferably all lists. If sorting isn't made the default, we'd prefer a configuration to allow an admin to enable this as default as it's what the users expect.

The sorting is probably easy to implement in dCache View. I've personally had great success using the minimalistic https://github.com/tofsjonas/sortable for my simpler projects, performance has never been an issue even with huge tables. I especially find the data-sort attribute useful to get sizes/dates sorted right, but also to implement groupings with for example directories sorted before files etc.

**Comment by alrossi** [comment]
I cannot speak to how easily the files/directories view can be sorted, since it does not use the table libraries that the admin pages use.

Most of the admin pages, on the other hand, have both sorter buttons on relevant fields, but in most cases also should arrive from the the server in lexicographically sorted order by default (note that there is also paging going on). It has been rather puzzling why the Polymer component (for instance, in the cells view) sometimes scrambles the order sent by the server.   Unfortunately this has not been a great priority to fix, since one can click the sorter arrow to rectify this, inconvenient as that may be.  

However, the user frustration is certainly understandable, certainly regarding directory listing.  

Hopefully we will have the developer hours available soon to devote to improvements of dCacheView.

**Comment by ZNikke** [comment]
The Polymer iron-list seems to lack sorting, I found lots of old issues requesting this but it seems it was never implemented. The common workaround seems to be to sort the input data.

I added a pull request with a rather quick&dirty workaround, but it should suffice for most of our users for now.
