### ISSUE TITLE
Share POST to / breaks in some setups

### ISSUE THREAD

**Issue by ZNikke** [dCache/dcache-view#287]
When trying to share a file a POST is made to / instead of the file location when trying to create the Macaroon.

This breaks on our setup where / is served by a static file (and confusingly also on our test setup where / is served by dCache).

A safer option seems to be doing a POST to the file location, as this is what other software like Rucio does it sees a lot more testing.

Will submit pull request with suggested fix.

**Comment by paulmillar** [comment]
This is just some extra info -- just in case you don't already know this.

The [macaroon request API](https://www.dcache.org/manuals/UserGuide-8.2/webdav.shtml#requesting-macaroons) accepts a POST request (with the correct `Content-Type` header) on any arbitrary path: even paths that currently do not exist.

If the request path is not `/` then dCache will add the request path as a `path` caveat in the macaroon.

If the request path is `/` then no `path` caveat is added automatically.  In this case, a `path` caveat (something that is very likely desired) would need to be added explicitly in the POST request body.

IIRC dCache View targets `/` because it was easier to manage the set of desired caveats and submit them in one place (the JSON body of the POST request).  However, otherwise there is no strong reason to target `/`.
